title: Tien Tran # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | Machine Learning Engineer  
  <br><br>
  MS in Data Science | Illinois Institute of Technology '19
  <br><br>
  <a href="https://www.linkedin.com/in/tien-m-tran/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
